config/routes.rb
Rails.application.routes.draw do

  root "dashboard#index"
  get 'conversations/index' => 'conversations#index'
  get '/send_message' => 'conversations#send_message'

  resources :clients do
    resources :conversations
  end

  resources :users do
    resources :conversations
  end

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end




end
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

app/models/conversation.rb
class Conversation < ActiveRecord::Base

  belongs_to :user
  belongs_to :client
  

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  before_action :layer_platform

  def index
      @user = current_user
      @conversations = @layer_platform.users.find(@user.id).conversations.list #retieving all conversations for this user on Layer

  end

  def show
      @user = current_user
      @conversation = Conversation.find_by(:conversation_id => params[:conv_id])
      @client = Client.find_by(:conversation_id => params[:conv_id])
      @conv = @layer_platform.users.find(@user.id).conversations.find(@conversation.conversation_id).messages.list #retrieving specific conversation from Layer
      respond_to do |format|
          format.js
      end
  end

  def create
    create_conversation
  end

    def send_message
      @user = current_user
      @message = input  #submited from form
      message = {
        sender: {
          name: @user.username
        },
        parts: [
          {
              body: @message,
              mime_type: "text/plain"
          },
          # {
          #     body: "YW55IGNhcm5hbCBwbGVhc3VyZQ==",
          #     mime_type: "image/jpeg",
          #     encoding: "base64"
          # }
        ],
        notification: {
          text: "You have a new message",
          sound: "chime.aiff"
        }
      }

      @conv = @layer_platform.conversations.find(params[:conversation_id])
      @conv.messages.create(message)
    end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_show.html.erb
<div class="conversation-header panel-header">
  <div class="title">
    <span>Advices for <%= @client.first_name %></span>
  </div>
</div>

<div class="message-list">
  <% @conv.each do |message| %>
    <div class="message-item">
      <div class="avatar">
        <span>
          <% if message.send.name == @user.username %>
            <%= image_tag @user.avatar.url(:thumb) %>
          <% else %>
            Client
          <% end %>
        </span>
      </div>
      <div class="main">
        <span class="name"><%= message.sender.name %></span>
        <div class="message-parts">
          <div class="bubble text"><%= message.parts.body %></div>
        </div>
      </div>
      <span class="timestamp">
        <span><%= message.sent_at %></span>
        <span class="message-status">
          <% if message.is_unread == true %>
            <%= "unread" %>
          <% else %>
            <%= "read" %>
          <% end %>
        </span>
      </span>
    </div>
  <% end %>
</div>

<div class="typing-indicator-panel">
</div>
<div class="message-composer">
    <%= form_tag("/send_message", method: "get") do %>
          <%= label_tag(:q, "New message:") %>
          <%= text_field_tag(:q) %>
          <%= hidden_field_tag 'conversation_id', @conversation.conversation_id %>
          <%= submit_tag("Send") %>
    <% end %>
</div>

app/views/conversations/index.html.erb
<!-- Refreshing the page every few seconds could be great for new messages to appear right after being sent -->
    <div id="root" class="main-app">
      <div class="messenger">

        <div class="left-panel">
          <div class="panel-header conversations-header">
            <div class="title">
              <span><%= @user.username %>'s conversations</span>
            </div>
          </div>
          <div class="conversation-list">
            <% @conversations.each do |conversation|  %>
              <%= link_to user_conversation_path(:conv_id => conversation.uuid), :remote => true, :class => "participant selected-conversation" do %>
                  <div class="avatar cluster">
                    <span><%= @user.username %></span>
                    <span>AL</span>
                     <!-- harcoded, need to find a way to retrieve client name from database for each conversation -->
                  </div>
                  <div class="info">
                    <div class="main">
                      <span class="title">Advices for Alice</span>
                      <!-- hardcoded here as well, same issue -->
                    </div>
                  </div>
              <% end %>
            <% end %>
          </div>
        </div>


        <div class="right-panel">

            <%= render partial: 'show', locals: { conv: conv} %>

        </div>
      </div>
    </div>

app/views/conversations/show.js.erb
$(".right-panel").html("<%= escape_javascript(render partial: 'show', locals: { conv: @conv } ) %>");